# -*- coding: UTF-8 -*-

__author__ = 'Bruce Frank Wong'


from peewee import (
    AutoField,
    CharField,
    FixedCharField,
    DateField,
    TimeField,
    BooleanField,
    IntegerField,
    FloatField,
    ForeignKeyField,
)

from .base import BasicModel


class Broker(BasicModel):
    pass


class CapitalAccount(BasicModel):
    """
    Capital account, generated by exchange.
    """
    id = AutoField(primary_key=True)


class InvestorAccount(BasicModel):
    """
    Investment account.
    """
    id = AutoField(primary_key=True)
    broker = FixedCharField(verbose_name='证券/期货公司', max_length=4)
    symbol = ForeignKeyField()


class Portfolio(BasicModel):
    id = AutoField(primary_key=True)
